export const recommendedHabits = [
  {
    name: 'Wake up early',
    description: 'Rise at 6:00 AM to start the morning energized',
    icon: 'SunMedium',
    color: '#F59E0B',
    category: 'Health',
    frequency: 'daily',
    target: 1,
    unit: 'time',
  },
  {
    name: 'Exercise & Workout',
    description: '30 minutes cardio or strength training',
    icon: 'Dumbbell',
    color: '#EF4444',
    category: 'Fitness',
    frequency: 'custom',
    customDays: [1, 2, 3, 4, 5], // Mon - Fri
    target: 30,
    unit: 'mins',
  },
  {
    name: 'Coding & Building',
    description: 'Write clean code and contribute to projects',
    icon: 'Code2',
    color: '#6366F1',
    category: 'Learning',
    frequency: 'daily',
    target: 60,
    unit: 'mins',
  },
  {
    name: 'Read Books',
    description: 'Read at least 20 pages of non-fiction or technical book',
    icon: 'BookOpen',
    color: '#3B82F6',
    category: 'Learning',
    frequency: 'daily',
    target: 20,
    unit: 'pages',
  },
  {
    name: 'Drink 3L Water',
    description: 'Stay hydrated throughout the day',
    icon: 'Droplets',
    color: '#06B6D4',
    category: 'Health',
    frequency: 'daily',
    target: 3,
    unit: 'liters',
  },
  {
    name: 'Mindful Meditation',
    description: '10 minutes of deep breathing and calm mindfulness',
    icon: 'Sparkles',
    color: '#8B5CF6',
    category: 'Personal',
    frequency: 'daily',
    target: 10,
    unit: 'mins',
  },
  {
    name: 'Daily Journaling',
    description: 'Reflect on wins, learnings, and gratitude',
    icon: 'PenLine',
    color: '#EC4899',
    category: 'Personal',
    frequency: 'daily',
    target: 1,
    unit: 'entry',
  },
  {
    name: 'Review Daily Goals',
    description: 'Plan the upcoming day and check off completed tasks',
    icon: 'CheckCircle2',
    color: '#10B981',
    category: 'Work',
    frequency: 'daily',
    target: 1,
    unit: 'time',
  },
];
